### PR TITLE
Added a Paper and Cheese Pun

### PR DESCRIPTION
**Pull request by MLeongQA**
Added two branches, FEATURE-CHEESE and FEATURE-PAPER with two juicy puns.

### CODE REVIEW

**Review by TheEarlOfGray — APPROVED** [review]
legendary...

**Review by JAgyei-Burobey — COMMENTED** [review]
Excellent, 10/10

**Review by songdaeng — COMMENTED** [review]
Good stuff

**Review by AfroDan91 — APPROVED** [review]
nice one

**Review by songdaeng — APPROVED** [review]

**Review by JAgyei-Burobey — APPROVED** [review]
Excellent

**Pull request merged**
