### PR TITLE
Added Pun1 and Pun2 to my dev branch

### PR DESCRIPTION
**Pull request by AfroDan91**

### CODE REVIEW

**Review by MLeongQA — APPROVED** [review]
10/10 Puns

**Review by JAgyei-Burobey — COMMENTED** [review]
A hearty chuckle, 10/10

**Review by TheEarlOfGray — APPROVED** [review]
epic...

**Review by songdaeng — COMMENTED** [review]
good pun

**Review by songdaeng — APPROVED** [review]
Good one

**Pull request merged**
